### ISSUE TITLE
Please consider updating installation guide

### ISSUE THREAD

**Issue by gmk57** [tttppp/mountain_tapir#28]
AFAIK, `easy_install` is effectively deprecated. I also had some errors due to missing `tkinter` and `ImageTk`.

Here is what worked for me on Linux Mint 20 (should also work on Ubuntu 20.04):
```
apt install python3-pip python3-pil.imagetk
pip3 install mountain_tapir
```
Thanks for your app, it works fine. :)

**Comment by tttppp** [comment]
Brilliant! Thanks for the information. I'll update the docs site.

Really glad you got Mountain Tapir to work!
